### ISSUE TITLE
[BUG] Sync: Fail with error 'ERC1155: burn amount exceeds balance'

### ISSUE THREAD

**Issue by sir-canada** [sunflower-land/sunflower-land#920]
This is only for anyone who is having trouble syncing in the last few days with "ERC1155: burn amount exceeds balance" contract error. Please do not post in this thread if you are getting any other issue. You can tag me in discord regarding other issues.

If you get "**SunflowerLand: Deadline Passed**," it is because you did not put a high enough gas fee, and it took too long to process the transaction. Increase GWEI or select high/aggressive. Or wait for polygon to be less busy.

If you simply get an abnormally high gas fee, I recommend adjusting your gas limit to 800,000 and see if you get the error in the title.

----

For those affected, to make this easier for the developers to determine the cause and fix this, please reply with 
1. your farm ID 
2. your latest sync polygonscan TX,
3. whether you sold crops before halvening and didn't sync for over 24 hours following the sale

**In this format:**
Farm ID 26532 (Mentalcraft)
https://polygonscan.com/tx/0xc06af7b9df3f490315a2c168d90d45d1a0381c01182932630a55a47173cd02c2
:heavy_check_mark: Sold crops before halvening and did not sync within 24 hours

**Comment by sir-canada** [comment]
Farm ID 103099
https://polygonscan.com/tx/0x1a119b1eea936df9867a540cf3b4172f04dac621cf080eb5debaf5f4dc453586
:heavy_check_mark: Sold crops before halvening and did not sync within 24 hours

**Comment by Ymarco7** [comment]
FARM ID #4553
0xaf9b13b9b904afb9c09eb974fd7e7261bc7568b6a3fa29b673946f93338011f0
 Sold crops before halvening and did not sync within 24 hours

**Comment by jahernan1** [comment]
Farm ID 8569
https://polygonscan.com/tx/0x80321042aa055d7ab5209888aa09c6bb301c97dda57a565e9e06e5836dd7a1b5
✔️ Sold crops before halvening and did not sync within 24 hours 
      -> I synced successfully just before the halvening(Monday, May 9, 2022 11:59 PM UTC) at May-09-2022 09:42:50 
           PM+UTC 
          - txn:0x7a37adea61c86b23ac6ad6d19c5a9778cedf00280732fcad7d5169dd4c05460d with the old 
             contract: 0x157974ec4396fa687f9e094a93ec73da205f4351

The new smart contract seems to be estimating the gas limit at 29M for us with issues, thats why the fee is so high. In order to even make the transaction work I manually set the gas limit in MM to be sufficiently high 1M but much lower, regardless of this the transaction fails with smart contract error: 'ERC1155: burn amount exceeds balance'. Look at screenshot and you see that it never reaches gas limit, although it still used 500k. 

<img width="641" alt="Screenshot 2022-05-14 230715" src="https://user-images.githubusercontent.com/87386180/168458756-5f5746e8-4251-4d85-a5dd-62288de01376.png">
<img width="701" alt="Screenshot 2022-05-14 230748" src="https://user-images.githubusercontent.com/87386180/168458757-1a5b137e-6ff6-4f0a-b0f2-bb67698e136b.png">

We have tried many things that have been suggested from discussions on discord, including: resetting metamask, clearing browser cache, logout of SFL and re-sign, syncing clock, and using other web browsers(chrome, brave,edge). I have even deleted and redownloaded my MetaMask account and reset my computer. I have also seen other users resetting back to last sync and lose all  progress without fixing the issue, this is why i have not done it because it is not guaranteed at this point.

**Comment by jroks28** [comment]
Farm #49917
https://polygonscan.com/tx/0x1da32221c6ac8017ec61ec966997805f154a08c503df7194a49c26bc368cecd7
Last sync 5/9/2022, good sync but no restocking of seeds, then halving comes and not able to sync again since then upto this day 5/15/2022. Almost 25 failed transaction.

**Comment by DOCTHORhez** [comment]
Farm #26532
https://polygonscan.com/tx/0xce349af47d5f296b8c164225310355766963658e45ea55f7c7d696b8b143cee1
✔️ Sold crops before halvening and did not sync within 24 hours

**Comment by koxandroll** [comment]
Farm ID 21445
https://polygonscan.com/tx/0xcf0c78936548d80047b62329244c295910f79154132f7710fc0692f5eafe1cd0
✔️ Sold crops before halvening and did not sync within 24 hours

**Comment by Lastrato** [comment]
Farm ID 20331
https://polygonscan.com/address/0x6248b8abE10a4bE3eebD7F52e5ea0ecCD6a01E38
✔️ Sold crops before halvening and did not sync within 24 hours

**Comment by 0xFannie** [comment]
Farm ID 73318
https://polygonscan.com/tx/0xbddb50dcf0e99235ed37e69b208d632234e0d2da7765f0e546b219511c8d555f
Did not sold crops within 24 hours

Meet this problem since 7 days ago. Please check https://polygonscan.com/address/0xf9147fb1c9799fa61bc9a41b28fff2ee80654fd5

**Comment by victorsilab** [comment]
Farm ID 24659
https://polygonscan.com/tx/0x960f264283d715ba3eb85f5d1619504898f0749054b42fe8716d4b2bf9455641 
 not sold crops within 24 hours

**Comment by eetrtscompany** [comment]
Farm ID 3443
https://polygonscan.com/tx/0x783488adc03ee2e558f82294a71d6d0e94692503200f9322df45f4ff3abf45da
Sold crops before halvening and did not sync within 24 hours

**Comment by sir-canada** [comment]
> Farm ID 24659 https://polygonscan.com/tx/0x960f264283d715ba3eb85f5d1619504898f0749054b42fe8716d4b2bf9455641 not sold crops within 24 hours

Hi, thank you for posting a response! Just wanted to note, your polygonscan sync fail is this one here:
https://polygonscan.com/tx/0xce9fcf1e4b99c920f12d421194520210fb234fae60f0358bb4f60168fb207eea

**Comment by victorsilab** [comment]
> > Farm ID 24659 https://polygonscan.com/tx/0x960f264283d715ba3eb85f5d1619504898f0749054b42fe8716d4b2bf9455641 not sold crops within 24 hours
> 
> Hi, thank you for posting a response! Just wanted to note, your polygonscan sync fail is this one here: https://polygonscan.com/tx/0xce9fcf1e4b99c920f12d421194520210fb234fae60f0358bb4f60168fb207eea

thanks, i edited my post

**Comment by sir-canada** [comment]
> Farm ID 20331 https://polygonscan.com/tx/0xbbed182cd53290a5258e065f772a3e93373dfa31f9226a9bc2446f6e8feba507 heavy_check_mark Sold crops before halvening and did not sync within 24 hours

Hi, the error you are currently reporting is caused by too low a gas fee. Please select 'high/aggressive' to try to submit your sync transaction again.

**Comment by sir-canada** [comment]
Posting for others who were not able to post here:

benedict 116641
https://polygonscan.com/tx/0xfb07082b025e85c9a2435cdb68d6d0225ad99e04a98b0965654a066f02c51650

koxan 21445
https://polygonscan.com/tx/0xcf0c78936548d80047b62329244c295910f79154132f7710fc0692f5eafe1cd0

karalov 18984
https://polygonscan.com/tx/0x98f343f65c0db4e78ce6eb142f5d41016e278b60ab3751164188c86373420f73

erick jegeur 10724
https://polygonscan.com/tx/0xa53d79310a894a0e3c3ce4188681957e5ccb03ef888f26e6a80fb10066ad21e0

**Comment by Lastrato** [comment]
> > Farm ID 20331 https://polygonscan.com/tx/0xbbed182cd53290a5258e065f772a3e93373dfa31f9226a9bc2446f6e8feba507 heavy_check_mark Sold crops before halvening and did not sync within 24 hours
> 
> Hi, the error you are currently reporting is caused by too low a gas fee. Please select 'high/aggressive' to try to submit your sync transaction again.

I edited my post (but same problem) thank you !

**Comment by secrett8** [comment]
Farm ID 24219
0xcc6bf8981561382fd92457d156de865cdf4ec5316e5e7b416c42f0dbab0c6386
✔️ Sold crops before halvening and did not sync within 24 hours

**Comment by andjik11** [comment]
Farm ID 18258 
https://polygonscan.com/tx/0xf3d2a1824424332bc74451ea4d8d34db3a1cd2a874f97fe10b85e6a765baa900
 Sold crops before halvening and did not sync within 24 hours

**Comment by bleedgreen22** [comment]
FARM ID 5645 
Transaction: https://polygonscan.com/tx/0xafe09c8f9bb4661e64c3b4b0331ed74c85dd28c4b9cc57d11fa777409b6bac66
Sold Crops before halvening (a couple of hours before) did not sync within 24hours

**Comment by adamhannigan** [comment]
Thank you everyone for these comments 🙏 The level of detail + transactions makes this extremely useful to debug. The team is working on this today and hopefully will have this resolved quickly

**Comment by adamhannigan** [comment]
We have pin pointed the issue to when the latest smart contracts were released with security improvements. It looks like you all previously synced just before the new smart contracts went live.

It looks like your accounts did not start a new session, but were continuing on from a previous session's progress.

We will need to write a script to rectify your accounts. The team has just started on this and hopefully will be done today 🙏

**Comment by Lastrato** [comment]
> We have pin pointed the issue to when the latest smart contracts were released with security improvements. It looks like you all previously synced just before the new smart contracts went live.
> 
> It looks like your accounts did not start a new session, but were continuing on from a previous session's progress.
> 
> We will need to write a script to rectify your accounts. The team has just started on this and hopefully will be done today 🙏

My god I thought we had been forgotten thank you!! Good luck with the work !

**Comment by purplestar29** [comment]
1. #72748
2. 0x2f0d878760da952f4e7e9eb9d5bb4193904d0ef5
3. Not sure

**Comment by Vingador7** [comment]
#26871
https://polygonscan.com/tx/0x98e5d028a0c284eb270f2585197e7c5316a15f0915bf5057c1480cbf9225b1a7
Sold crops before halvening and did not sync within 24 hours

**Comment by victorsilab** [comment]
> We have pin pointed the issue to when the latest smart contracts were released with security improvements. It looks like you all previously synced just before the new smart contracts went live.
> 
> It looks like your accounts did not start a new session, but were continuing on from a previous session's progress.
> 
> We will need to write a script to rectify your accounts. The team has just started on this and hopefully will be done today 🙏

Thanks :)

**Comment by aizenSEPx** [comment]
#26521
https://polygonscan.com/tx/0xeab7e9310ba37e1e4d1e1ccac283bcd3341f8ba3b4e94f6f19f55db6e37ab0c9
Sold crops before halvening and did not sync within 24 hours

**Comment by kja77** [comment]
1.Farm ID 14831
2.https://polygonscan.com/tx/0x5dfb6387a056b582d732f5cfa075da11f4f95921efcbd527b77edd9cb6a55434
3.Not sure

**Comment by sir-canada** [comment]
celpangilinan 42102
https://polygonscan.com/tx/0xb02aaecc56a5f32e41c4da90ca8bb4398f15a7881bbe117b58a10d5341a2d1d6

**Comment by slydougie** [comment]
FARM ID:61258   (Sly#9447)
https://polygonscan.com/tx/0x33d21d3b92b4260f5be47c069cefc7c95d185c36280cf14794c23410eea3a9c8

**Comment by pirogello** [comment]
FARM ID #11077 (pirogello#1369)
https://polygonscan.com/tx/0x6bf9139437119679082aa4379620dea02cb85fd4a759b06160c93de52444d2c7
Sold crops before halvening and did not sync within 24 hours

**Comment by vlad113rm** [comment]
Farm ID 10714
https://polygonscan.com/tx/0xb82d553b75b2baf7e5c49cbc656d6a46cb1436c3dd029880e938277a66f17151
✔️ Sold crops before halvening and did not sync within 24 hours

**Comment by vlad113rm** [comment]
FARM ID #10714
https://polygonscan.com/tx/0x83afd293a11982153648d7be3c346bc7be3c9c256cef8372ce7e310084717f97
Sold crops before halvening and did not sync within 24 hours

**Comment by rpdo001** [comment]
FARM ID #54977
https://polygonscan.com/tx/0x22a4c19cca519b2b6b0261ae8a158aacaff73f607ea233c95b52dd3421df4ab0
Sold crops before halvening and did not sync within 24 hours

**Comment by Narcobr** [comment]
FARM ID #127320
https://polygonscan.com/tx/0x9c9296b4ac17490942754f1499c2fe40febe3c139b279e7cc6ef67ab37fc8bd2
TX id 0x9c9296b4ac17490942754f1499c2fe40febe3c139b279e7cc6ef67ab37fc8bd2

**Comment by Diayex** [comment]
Farm ID #104588
https://polygonscan.com/tx/0xa80e8db262feeab3d8124d621745a667fa69193ce0365fb564f77feeb5b2c1fd
I can only find TX where I have the error "SunflowerLand: Deadline Passed" even though I'm having way high gas fees (I don't know how to find the correct TX) but it's been more than a week that I am experiencing this issue (I reset my progress twice and it didn't work)
✔️ Sold crops before halvening and did not sync within 24 hours
![image_2022-05-16_182125448](https://user-images.githubusercontent.com/105665025/168648365-a5bbe094-f8cb-42bf-944a-e6fcd48519be.png)

**Comment by Labochi** [comment]
@adamhannigan Do we have an update on this? Thanks.

**Comment by adamhannigan** [comment]
Hey all, for those facing the `'ERC1155: burn amount exceeds balance'` error could you please try sync again 🙏 

The team has rectified a few of the issues that were causing this.

For separate sync issues, we are still investigating

**Comment by Ymarco7** [comment]
Still not working for me.
Below is my latest sync attempt.
https://polygonscan.com/tx/0x9f36eb56d811a52a4e057098380e42c8eb8addc4d5943cdf786aed2af241a789

**Comment by adamhannigan** [comment]
> Still not working for me. Below is my latest sync attempt. https://polygonscan.com/tx/0x9f36eb56d811a52a4e057098380e42c8eb8addc4d5943cdf786aed2af241a789

<img width="427" alt="Screen Shot 2022-05-17 at 7 29 43 pm" src="https://user-images.githubusercontent.com/11745561/168779042-d1beac2e-b575-4abc-b0b5-4c04b0142656.png">

Thanks for raising this. It looks like this is a different issue than the one we just fixed. We are looking into the other sync issues like this one now

**Comment by Ymarco7** [comment]
Thanks, yes, its a new error message different from the previous error i had. Which is the erc1155.

**Comment by jroks28** [comment]
Still not working. Farm#49917
https://polygonscan.com/tx/0x4bfef6a4168cdae389f632cbff48f89cbc9dabd3d7e89d021b9377e63e213978

**Comment by Diayex** [comment]
> Hey all, for those facing the `'ERC1155: burn amount exceeds balance'` error could you please try sync again 🙏
> 
> The team has rectified a few of the issues that were causing this. Please try and let us know if it now works
> 
> For separate sync issues, we are still investigating

Hello, just tried, didn't work for me https://polygonscan.com/tx/0x8236119660569ea2283d6ad18d4ffa62fe729474ffec1d9d5f567705b3a782b3

**Comment by purplestar29** [comment]
Farm #72748 (Purplestar#2182)

I tried it an still not working for me either.

Here is my last transaction:

https://polygonscan.com/tx/0x5c5949a96f07f56a57b7a32340b89fe5a58876b38e12ce8658a61fd3eaaebcce

Fail with error 'ERC1155: burn amount exceeds balance'

**Comment by sir-canada** [comment]
nikitakodyrev 45192 still getting same error ERC1155: burn amount exceeds balance'
https://polygonscan.com/tx/0x771ce1c352f64d776f7c3c7a50258e05dbe8f60adbdf7ae352ae5b1865080588

also reporting 4 others problem was fixed and are very happy.

**Comment by sir-canada** [comment]
erick jegeur 10724
https://polygonscan.com/tx/0x770e720420f99c8efbb1e9acddfdba2fb076783cdbf02b0f41367b6ad9bddd16

**Comment by Flyug** [comment]
FARM ID #76034
https://polygonscan.com/tx/0xdca67aac998f7139e9b87cd88cedbfff4f900e55fc0476b2201c428a035212cc
Fail with error 'ERC1155: burn amount exceeds balance'

**Comment by sir-canada** [comment]
FATE 49139
https://polygonscan.com/tx/0x81bebabc27ea76727383ff422cb45a5a44811d061f37cbb45059e2dc2eb7ce29
Fail with error 'ERC1155: burn amount exceeds balance'

**Comment by Prosto4ek0990** [comment]
FARM ID 20069
https://polygonscan.com/tx/0x87fed41795ab692187d693cd4b3bc4e4ea3d40e9c3b94cb0323facc38ac26538
✔️ Sold crops before halvening and did not sync within 24 hours

**Comment by sir-canada** [comment]
turkeybrah 5524
Fail with error 'SunflowerLand: Item mint exceeds max mint amount'
https://polygonscan.com/tx/0x34e775d11a7ab78020a5cabb29d95de32d6eaaecc81eb99606dc6bddce478094

different error, but same error as Ymarco7

**Comment by pavlo99999** [comment]
Farm ID 84237
https://polygonscan.com/tx/0x6ee34bcaec38990c86430bba457043bff27f46605c85817f156582742b71a199
Error with error "SunflowerLand: deadline expired"

**Comment by jahernan1** [comment]
> Hey all, for those facing the `'ERC1155: burn amount exceeds balance'` error could you please try sync again 🙏
> 
> The team has rectified a few of the issues that were causing this. Please try and let us know if it now works
> 
> For separate sync issues, we are still investigating

the issue is still persistent, just wasting matic on failed transactions...
farm id 8569
latest failed tx: 0x70ee310574d7b59b245ce96594ddd0cc8e2106d3

<img width="645" alt="image" src="https://user-images.githubusercontent.com/87386180/168929837-30e27f3e-b0d5-4840-bd1a-f4a81816a4e9.png">

**Comment by adamhannigan** [comment]
Thanks for your patience everyone. 

We discovered that during our recent smart contract updates, in some cases our game server data became out of sync with farm data on the blockchain.

For example, our game server and UI would show 5 pumpkin seeds when the blockchain had 0 seeds. When the user planted and harvested these items, the blockchain would throw an error during sync since these items never existed.

For those facing a sync issue "Burn amount exceeds balance", please try to sync again. We expect your inventory to be inline with the blockchain after your next sync is successful. 

Bugs: 0 🐛 
Devs: 1 💪

**Comment by purplestar29** [comment]
Farm #72748 (Purplestar#2182)

I just tried to sync and it worked this time. Thanks

**Comment by Ymarco7** [comment]
> 

Still failed to sync, burn amount exceeds 😔

**Comment by Ymarco7** [comment]
> > 
> 
> Still failed to sync, burn amount exceeds 😔

Last transaction
https://polygonscan.com/tx/0xd51705fcd1bfef457e02bf5e401f59520b00b2c620068839babe16eb1dc759b8

**Comment by jroks28** [comment]
Good day! Everyone, just want to share my syncing issue is now solve.. Thanks for the hard work dev. Happy farming..
https://polygonscan.com/tx/0x4bfef6a4168cdae389f632cbff48f89cbc9dabd3d7e89d021b9377e63e213978

**Comment by Ymarco7** [comment]
> Thanks for your patience everyone.
> 
> We discovered that during our recent smart contract updates, in some cases our game server data became out of sync with farm data on the blockchain.
> 
> For example, our game server and UI would show 5 pumpkin seeds when the blockchain had 0 seeds. When the user planted and harvested these items, the blockchain would throw an error during sync since these items never existed.
> 
> For those facing a sync issue "Burn amount exceeds balance", please try to sync again. We expect your inventory to be inline with the blockchain after your next sync is successful.
> 
> Bugs: 0 🐛 Devs: 1 💪

![Screenshot_2022-05-18-14-27-44-62_e4424258c8b8649f6e67d283a50a2cbc](https://user-images.githubusercontent.com/105577622/168972114-f97b1943-b96c-42ea-9c74-2ead473d64c8.jpg)
Heres the new error im getting, btw

**Comment by adamhannigan** [comment]
We have just needed to revert the fix for this. It was related to the recent burn issue we announced.

We know the problem, we just need to solve it differently and will need a bit more time 🙏

**Comment by Ymarco7** [comment]
> 

Appreciate the great work Adam. And dev team. Thanks

**Comment by oldtora** [comment]
23718
https://polygonscan.com/tx/0xd8345a6727146ef705cfda7993461f0c23e1967414b072189262476143bfc8fc
Sold crops before halvening and did not sync within 24 hours

**Comment by rpdo001** [comment]
I still get the error, can I check it please

FARM ID #54977

https://polygonscan.com/tx/0x4467624794cdeaf9aba59375ad78cf4d1c345da8af85198e4f558542ad111ac9

**Comment by jahernan1** [comment]
> Thanks for your patience everyone.
> 
> We discovered that during our recent smart contract updates, in some cases our game server data became out of sync with farm data on the blockchain.
> 
> For example, our game server and UI would show 5 pumpkin seeds when the blockchain had 0 seeds. When the user planted and harvested these items, the blockchain would throw an error during sync since these items never existed.
> 
> For those facing a sync issue "Burn amount exceeds balance", please try to sync again. We expect your inventory to be inline with the blockchain after your next sync is successful.
> 
> Bugs: 0 🐛 Devs: 1 💪

The issue is not fixed for me, I dont understand what is going on with my farm, please help, I have over 100 sfl progress, most of which i have burned for crops and mining gold, cant sync for 8 days now, cant get lp bonuses for 2 cycles, cant farm anymore. 

I have faith in the team but at this point i put my faith in you guys to fix it and did not reset session and now I feel like if i reset its just too sad with all the progress i have made, i put a ticket for the issue and the only solution is reset session.

I again tried three different browsers, burned through almost 0.5 matic in failed transactions and am feeling a bit demoralized at this point, if you tell me to just reset i will but i want to make sure you understand how much i am losing and how upsetting this will be. I still have faith in you guys and the game but still sad. 

farm id 8569
Heres my latest failed txn: 0x0b1bddf2fbfe03ed18bd0e100d02a8e048b4fe3ae90bacbe962f3ba27cb85b42

<img width="728" alt="image" src="https://user-images.githubusercontent.com/87386180/169106915-74256a2b-97b3-44a5-addf-634ab2f86f4b.png">

**Comment by Ymarco7** [comment]
Just tried to sync and it worked perfectly this time 🙂, thanks a lot

**Comment by Labochi** [comment]
![image](https://user-images.githubusercontent.com/103340944/169194618-c1104ceb-9f7d-41b0-8783-8fa7f1bf7e2e.png)

**Comment by jahernan1** [comment]
> ![image](https://user-images.githubusercontent.com/103340944/169194618-c1104ceb-9f7d-41b0-8783-8fa7f1bf7e2e.png)

I am still getting the same error as before.

**Comment by sir-canada** [comment]
Erick Jegeur 10724   Fail with error '**ERC1155**: burn amount exceeds balance'
https://polygonscan.com/tx/0x1e4c6114aea127ed7eeff2bf936163431b8badd606c604cf5379eb8d3226bcf9

Tux 45258        Fail with error '**ERC20**: transfer amount exceeds balance'
https://polygonscan.com/tx/0x8cdfa50edda07c46b454a7967a719ca8bed1fa725d4d45575525fdbe9fcf1f26

**Comment by sir-canada** [comment]
kja77 14831 Fail with error '**ERC1155**: burn amount exceeds balance'
https://polygonscan.com/tx/0xf7d2d9575674e6a4607d9839614f38ce498ecf6c6871ae3162ccc7f425b5862b

**Comment by sir-canada** [comment]
Calebaby 22284
https://polygonscan.com/tx/0xe49e2b73da417ebaa73051e7e2fda0d2c00f6b779f6e241b6cd7c79effd5be04

**Comment by kja77** [comment]
farm id 14831
I still can't sync. Last  succes transaction 9 may
https://polygonscan.com/tx/0xf7d2d9575674e6a4607d9839614f38ce498ecf6c6871ae3162ccc7f425b5862b
![sf1](https://user-images.githubusercontent.com/60600255/169589167-6043f4ce-0391-4346-a133-3618a9c8b156.jpg)
![sf2](https://user-images.githubusercontent.com/60600255/169589175-adaf3542-e187-4086-beec-46b1ee195383.jpg)

**Comment by adamhannigan** [comment]
Thank you for everyone posting details.

Update: 2 of the engineers have spent the last 2 days working on this issue. Our previous "fix" did work, but it also caused the issue of deposited items being burnt. Given the seriousness of these changes we are spending extra time now writing tests and manually testing our fix before we deploy it.

Thanks for your patience, this must be extremely frustrating not being able to play the game. We hope to get you farming as soon as possible 🙏

**Comment by kja77** [comment]
I finally synced. Thank you very much

**Comment by adamhannigan** [comment]
Thanks for your patience everyone.

The team has just ran a script to ensure your accounts are in sync with the blockchain. There were a few cases where users had more items or less than they should have.

If everyone could please try sync again it would be much appreciated. If it works or doesn't, please let us know 🙏 

The other issue we found was that some people attempted to perform the migration (before May 5th) but did not sync to the Blockchain as per instructions. Unfortunately these cases mean that the people missed the airdrop period and can no longer sync those items to the Blockchain - these accounts have also been reset to the initial state on the Blockchain.

**Comment by jahernan1** [comment]
> Thank you for everyone posting details.
> 
> Update: 2 of the engineers have spent the last 2 days working on this issue. Our previous "fix" did work, but it also caused the issue of deposited items being burnt. Given the seriousness of these changes we are spending extra time now writing tests and manually testing our fix before we deploy it.
> 
> Thanks for your patience, this must be extremely frustrating not being able to play the game. We hope to get you farming as soon as possible 🙏

YES! Finally able to sync thank you for all the hard work from the team to make this happen!
